(() => {
  'use strict';
  const D=window.Chapter02,$=id=>document.getElementById(id),KEY='ongdia.chapter02.v2';
  let saved=null;try{saved=D.restore(JSON.parse(localStorage.getItem(KEY)));}catch{}
  let s=D.initial(),queue=[],afterDialogue=null,target=null,modalReturn=null,toastUntil=0,last=0,tick=0;
  const held=new Set(),audio=new window.SceneAudio(),reduced=()=>s.settings.reduced||matchMedia('(prefers-reduced-motion: reduce)').matches;
  const portraits={'Bạn':'ban','Duyên':'duyen','Thảo':'thao','Mạnh':'manh','Minh Anh':'minh-anh'};
  const intros={
    gate:[['Duyên','Cô ơi… mưa còn lớn hơn lúc nãy.'],['Thảo','Hai em đi sát cô. Điểm tập kết ở trên đồi, nhưng phải chọn đường tới đó an toàn.'],['Mạnh','[Bộ đàm] Đường phía đông có nước tràn. Không đi hướng đó nữa.'],['Minh Anh','[Bộ đàm] Các nhóm từ trường tìm tuyến khác. Không ai tự ý đi qua vùng nước chảy.']],
    junction:[['Duyên','Có ba đường… Cầu treo gần nhất, còn đường Bắc xa quá.'],['Thảo','Không chọn chỉ vì gần. Trước hết, xem từng tuyến và ghép những gì mình quan sát được.']],
    hill:[['Duyên','Đường này không ngập, lại đi lên cao. Có khi tốt đấy.'],['Thảo','Quan sát từ khoảng cách an toàn. Đừng tới sát sườn đất.']],
    suspension:[['Duyên','Kìa! Nhìn thấy mái điểm tập kết rồi. Cầu vẫn đứng, mặt cầu còn khô.'],['Thảo','Đừng chỉ nhìn mặt cầu. Hãy nhìn dòng nước và khu vực xung quanh.'],['Mạnh','[Bộ đàm nhiễu] …cô Thảo… tôi đang kiểm tra… cầu…']],
    north:[['Duyên','650 mét… mình có kịp không?'],['Thảo','Xa hơn không có nghĩa là chậm hơn, nếu đó là đường chúng ta thực sự đi được.']],
    concrete:[['Thảo','Dừng ở bờ gần. Kiểm tra mặt cầu, mực nước và dòng chảy quanh trụ trước khi quyết định.']],
    highroad:[['Duyên','Cuối cùng đường xa nhất lại là đường mình đi.'],['Mạnh','Không phải vì nó xa. Vì hiện tại nó có điều kiện ổn định hơn và đã được kiểm tra.'],['Minh Anh','[Bộ đàm] Từ đó theo đường cao thêm khoảng ba trăm mét. Điểm tập kết ngay phía trước.']],
    refuge:[['Duyên','Mưa nhỏ hơn rồi… mình sắp tới nơi phải không?'],['Thảo','Ừ. Cả nhóm vẫn ở cùng nhau. Trước khi liên lạc, hãy nhớ những dấu hiệu đã giúp mình chọn đường.']]
  };
  function save(){try{localStorage.setItem(KEY,JSON.stringify(s));$('save').textContent='ĐÃ LƯU HÀNH TRÌNH';}catch{$('save').textContent='KHÔNG THỂ LƯU · VẪN CHƠI ĐƯỢC';}}
  function toast(text){$('location-toast').textContent=text;$('location-toast').classList.add('visible');toastUntil=performance.now()+4200;}
  const free=()=>s.started&&$('dialogue').hidden&&$('modal').hidden&&!s.complete;
  function objective(){
    if(s.complete)return 'Cả nhóm đã lên đường cao. Chương 02 hoàn thành.';
    if(!s.solved.includes(s.scene)&&window.Chapter02Puzzles.puzzles[s.scene])return 'Giải câu đố khu vực: '+window.Chapter02Puzzles.puzzles[s.scene].title+'. Quan sát manh mối trước khi mở đường.';if(s.crossed)return 'Theo đường cao lên điểm tập kết. Liên lạc với Minh Anh.';
    if(s.scene==='concrete')return 'Kiểm tra đủ ba điểm ở bờ gần. Qua cầu khi bác Mạnh xác nhận và các tuyến đã được đánh giá.';
    if(s.scene==='hill'||s.scene==='suspension')return 'Quan sát các dấu hiệu, đánh giá tuyến rồi trở lại ngã ba.';
    if(s.scene==='north')return 'Quan sát đường dự phòng và hỏi bác Mạnh về tình trạng hiện tại.';
    return 'Quan sát cả ba tuyến. Tìm đường lên điểm tập kết cùng cô Thảo và Duyên.';
  }
  function render(){const scene=D.scenes[s.scene];s.position.x=clampX(s.position.x);$('spots').hidden=!s.started;$('scene-name').textContent=scene.name;$('landscape').style.backgroundImage=`url('assets/chapter02/${scene.art}.png')`;$('landscape').style.backgroundPosition=scene.position||'center';$('objective').textContent=objective();$('progress').textContent=`${s.solved.length}/8 câu đố · ${s.clues.filter(id=>id!=='highroad-marker').length}/13 dấu hiệu`;$('spots').replaceChildren();
    for(const p of scene.spots){
      const button=document.createElement('button'),isArrow=p.type==='exit'||p.type==='cross';
      button.className='spot '+(isArrow?'route-arrow ':'')+(s.clues.includes(p.id)||s.solved.includes(p.puzzle)?'seen':'');
      button.style.left=p.x+'%';button.style.top=p.y+'%';button.dataset.spot=p.id;
      if(isArrow){
        const destination=D.scenes[p.to].name,puzzle=D.travelPuzzle(s.scene,p.to);
        button.setAttribute('aria-label','Đi tới '+destination);button.setAttribute('aria-describedby','tip-'+p.id);
        const icon=document.createElement('span');icon.className='arrow-icon';icon.textContent=p.x<30||p.id.startsWith('back-')?'←':p.y<65?'↑':'→';icon.setAttribute('aria-hidden','true');
        const tip=document.createElement('span');tip.id='tip-'+p.id;tip.className='arrow-tip';tip.setAttribute('role','tooltip');
        const name=document.createElement('strong');name.textContent=destination;tip.append(name);
        const note=document.createElement('small');note.textContent=puzzle&&!s.solved.includes(puzzle)?'Giải câu đố để mở đường':p.type==='cross'&&!D.canCross(s)?'Kiểm tra cầu và sắp đội hình':p.sub||'Bấm để đi tới';tip.append(note);button.append(icon,tip);
        button.dataset.edge=p.x<25?'left':p.x>75?'right':'middle';button.dataset.locked=String(!D.canTravel(s,p.to));
      }else{button.append(document.createTextNode(p.label));if(p.sub){const sub=document.createElement('small');sub.textContent=p.sub;button.append(sub);}}
      button.onclick=event=>{if(isArrow&&event.pointerType==='touch'&&!button.classList.contains('armed')){document.querySelectorAll('.route-arrow.armed').forEach(v=>v.classList.remove('armed'));button.classList.add('armed');return;}walkToSpot(p);};
      $('spots').append(button);
    }
    $('party').style.left=s.position.x+'%';$('party').style.top=s.position.y+'%';$('party').hidden=!s.started;$('manh-world').hidden=!s.started||!['north','concrete','highroad','refuge'].includes(s.scene);$('scene-caption').hidden=!s.started;$('mission').hidden=!s.started;$('sound').textContent='Âm thanh: '+(s.settings.sound?'bật':'tắt');
  }
  function speak(lines,done){held.clear();target=null;queue=lines.slice();afterDialogue=done||null;$('dialogue').hidden=false;advance();}
  function advance(){if(!queue.length){$('dialogue').hidden=true;const done=afterDialogue;afterDialogue=null;done?.();return;}const [who,text]=queue.shift();$('speaker').textContent=who.toUpperCase()+(text.startsWith('[Bộ đàm')?' · BỘ ĐÀM':'');$('line').textContent=text;$('portrait').src=`assets/characters/${portraits[who]||'thao'}/portrait.png`;if(text.startsWith('[Bộ đàm'))audio.play('radio');}
  function enter(to){if(!D.canTravel(s,to)){toast('Cần kiểm tra đủ các tuyến và có bác Mạnh dẫn đường.');return;}const first=!s.visited.includes(to);s.scene=to;s.position={...(D.scenes[to].spawn||{x:48,y:88})};if(first)s.visited.push(to);toastUntil=0;held.clear();target=null;render();save();if(first)speak(intros[to]||[]);else toast(D.scenes[to].name);}
  function start(resume){s=resume?saved:D.initial();s.started=true;if(!s.visited.includes(s.scene))s.visited.push(s.scene);s.settings.reduced ||= matchMedia('(prefers-reduced-motion: reduce)').matches;$('intro').hidden=true;render();save();audio.setEnabled(s.settings.sound);audio.start();if(s.complete)showResults();else if(!resume)speak(intros.gate);else toast('Tiếp tục tại '+D.scenes[s.scene].name);}
  const clampX=x=>{const margin=Math.max(12,Math.min(25,9500/$('stage').clientWidth));const zone=D.scenes[s.scene].walk||{min:margin,max:100-margin};return Math.max(Math.max(margin,zone.min),Math.min(Math.min(100-margin,zone.max),x));};
  function walkToSpot(p){if(!free())return;target={x:clampX(p.x),y:Math.max(78,Math.min(89,p.y)),action:()=>interact(p)};}
  function interact(p){audio.play('click');if(p.type==='puzzle'){openPuzzle(p.puzzle);return;}if(p.type==='exit'){const puzzle=D.travelPuzzle(s.scene,p.to);if(puzzle&&!s.solved.includes(puzzle)){openPuzzle(puzzle,()=>interact(p));return;}if(p.to==='concrete'&&!s.manh){speak([['Thảo','Mình hỏi bác Mạnh trước. Đừng tự đi tới cầu khi chưa có thông tin hiện tại.']]);return;}if(s.scene==='highroad'&&p.to==='concrete'){speak([['Mạnh','Tôi dẫn cả nhóm trở lại bờ gần. Đi đều và không dừng trên cầu.']],()=>enter('concrete'));return;}enter(p.to);return;}
    if(p.type==='clue'){if(!s.clues.includes(p.id)){s.clues.push(p.id);render();save();}speak([[p.speaker,p.text]]);return;}
    if(p.type==='decision'){judge(p.route);return;}
    if(p.type==='npc'){s.manh=true;save();speak([['Mạnh','Tôi vừa kiểm tra cầu phía Bắc và đường sau cầu. Hiện đường vẫn thông, chưa có nước tràn hay dấu hiệu hư hỏng rõ.'],['Thảo','Hai em vẫn quan sát ở đầu cầu. Mình chỉ qua sau khi kiểm tra đủ và thống nhất tuyến.'],['Mạnh','Tôi sẽ dẫn cả nhóm. Điều kiện có thể thay đổi, nên mình đi đều và nghe hướng dẫn mới nhất.']]);return;}
    if(p.type==='cross'){if(!s.solved.includes('concrete')){openPuzzle('concrete',()=>interact(p));return;}if(!D.canCross(s)){const missing=Object.entries(D.required).filter(([,ids])=>ids.some(id=>!s.clues.includes(id))).map(([r])=>D.scenes[r].name);speak([['Thảo','Chưa vội qua. '+(missing.length?'Còn dấu hiệu chưa quan sát ở: '+missing.join('; ')+'.':'Hãy đánh giá hai tuyến A, B và trao đổi với bác Mạnh trước.')]]);return;}speak([['Mạnh','Tôi đi đầu, sau đó cô Thảo, hai em đi sát nhau. Đi đều, không chạy và không đứng lại trên cầu.']],()=>crossing());return;}
    if(p.type==='finale')reflection(0);
  }
  function panel(title,html,closable=true){modalReturn=document.activeElement;held.clear();target=null;$('panel').innerHTML=`<div class="panel-top"><small>CHƯƠNG 02 · BA CON ĐƯỜNG</small>${closable?'<button id="close-panel" aria-label="Đóng bảng">Đóng ×</button>':''}</div><h2>${title}</h2>${html}`;$('modal').hidden=false;$('close-panel')?.addEventListener('click',closePanel);$('panel').focus();}
  function closePanel(){if(s.complete){$('modal').hidden=true;return;}$('modal').hidden=true;modalReturn?.focus();}
  function openPuzzle(id,done){
    const puzzle=window.Chapter02Puzzles.puzzles[id];
    if(!puzzle)return;
    if(s.solved.includes(id)){if(done)done();else toast('Câu đố đã giải. Đường đi tiếp đã được mở.');return;}
    const missing=(puzzle.requires||[]).filter(clue=>!s.clues.includes(clue));
    if(missing.length||(puzzle.guide&&!s.manh)){
      const names=missing.map(clue=>Object.values(D.scenes).flatMap(scene=>scene.spots).find(p=>p.id===clue)?.label||clue);
      panel(puzzle.title,'<p>Quan sát trước khi suy luận.</p><div class="entry">'+names.map(name=>'<p>◇ '+name+'</p>').join('')+(puzzle.guide&&!s.manh?'<p>◇ Trao đổi với bác Mạnh</p>':'')+'</div><p>Đóng bảng để tiếp tục khám phá. Manh mối đã tìm được sẽ được giữ.</p>');return;
    }
    let chosen=[];
    const content=puzzle.kind==='sequence'?'<p class="puzzle-instruction">Chọn các thẻ theo thứ tự đúng. Cần '+puzzle.answer.length+' thẻ.</p><ol id="puzzle-slots" class="puzzle-slots"></ol><div class="puzzle-cards">'+puzzle.options.map(([key,label])=>'<button data-card="'+key+'">'+label+'</button>').join('')+'</div>':puzzle.rows.map(([key,label])=>'<label class="match-row"><span>'+label+'</span><select data-match="'+key+'"><option value="">Chọn lời giải…</option>'+puzzle.options.map(([value,text])=>'<option value="'+value+'">'+text+'</option>').join('')+'</select></label>').join('');
    panel(puzzle.title,'<small>CÂU ĐỐ KHU VỰC · '+D.scenes[id].name+'</small><p>'+puzzle.intro+'</p>'+content+'<p id="puzzle-feedback" role="status"></p><div class="buttons"><button id="puzzle-submit" class="primary">Xác nhận lời giải</button><button id="puzzle-reset">Làm lại</button><button id="puzzle-hint">Gợi ý</button></div>');
    const refresh=()=>{if(puzzle.kind!=='sequence')return;$('puzzle-slots').replaceChildren();for(let i=0;i<puzzle.answer.length;i++){const item=document.createElement('li');item.textContent=puzzle.options.find(([key])=>key===chosen[i])?.[1]||'Chưa chọn';$('puzzle-slots').append(item);}document.querySelectorAll('[data-card]').forEach(button=>{button.disabled=chosen.includes(button.dataset.card)||chosen.length>=puzzle.answer.length;});};refresh();
    document.querySelectorAll('[data-card]').forEach(button=>button.onclick=()=>{chosen.push(button.dataset.card);$('puzzle-feedback').textContent='';refresh();});
    document.querySelectorAll('[data-match]').forEach(select=>select.onchange=()=>{$('puzzle-feedback').textContent='';select.title=select.selectedOptions[0].textContent;});
    $('puzzle-reset').onclick=()=>{chosen=[];document.querySelectorAll('[data-match]').forEach(select=>select.value='');$('puzzle-feedback').textContent='';refresh();};
    $('puzzle-hint').onclick=()=>$('puzzle-feedback').textContent=puzzle.hint;
    $('puzzle-submit').onclick=()=>{
      const answer=puzzle.kind==='sequence'?chosen:Object.fromEntries([...document.querySelectorAll('[data-match]')].map(select=>[select.dataset.match,select.value]));
      if(!window.Chapter02Puzzles.correct(id,answer)){$('puzzle-feedback').textContent='Chưa khớp với các chỉ dẫn. Hãy đối chiếu lại hoặc xem gợi ý; không mất tiến trình.';audio.play('wrong');return;}
      s.solved.push(id);save();audio.play('unlock');render();panel('Đường đi đã được mở','<small class="good">CÂU ĐỐ HOÀN THÀNH</small><p>'+puzzle.title+'</p><button id="puzzle-done" class="primary">'+(done?'Tiếp tục hành trình →':'Trở lại khu vực')+'</button>');$('puzzle-done').onclick=()=>{closePanel();done?.();};
    };
  }
  function judge(route){const ids=D.required[route];if(!ids.every(c=>s.clues.includes(c))){speak([['Thảo','Chưa đủ thông tin. Hãy quan sát tất cả dấu hiệu được đánh dấu ở khu vực này trước khi quyết định.']]);return;}
    const isHill=route==='hill';panel('Đường này có nên đi tiếp?',`<p>${isHill?'Đường lên cao và chưa ngập, nhưng đất đang cho thấy nhiều dấu hiệu bất thường.':'Điểm tập kết ở ngay bên kia. Mặt cầu khô, nhưng dòng nước đang tác động vào kết cấu.'}</p><div class="buttons"><button id="safe-choice" class="primary">${isHill?'Lùi khỏi sườn dốc':'Không qua cầu'} · Quay lại</button><button id="risk-choice">${isHill?'Tiếp tục đường đồi':'Qua cầu cho nhanh'}</button></div>`);
    $('safe-choice').onclick=()=>reason(route);$('risk-choice').onclick=()=>{closePanel();audio.play('thunder');speak(isHill?[['Thảo','Dừng lại. Mình không tiến vào sườn dốc đã có nhiều dấu hiệu bất ổn.'],['Duyên','Cô! Có đất đá vừa rơi ở phía trước…'],['Thảo','Cả nhóm đang ở ngoài chân dốc. Lùi về khu rộng rồi quay lại ngã ba.']]:[['Thảo','Không lên cầu. Dòng nước và cây trôi đang tác động vào phần bên dưới.'],['Duyên','Một khúc cây nữa… cầu vừa rung mạnh!'],['Thảo','Mình quan sát được từ bờ. Đừng đánh cược bằng việc bước lên cầu.']],()=>reason(route));};
  }
  function reason(route){const isHill=route==='hill';panel('Điều gì quyết định lựa chọn?',`<p>${isHill?'Vì sao nên tránh đường chân đồi?':'Vì sao mặt cầu khô vẫn chưa đủ để đi qua?'}</p><button class="option" data-answer="0">${isHill?'Vì đường này không có cầu.':'Vì mọi cây cầu treo đều nguy hiểm.'}</button><button class="option" data-answer="1">${isHill?'Vì cây nghiêng, đất nứt, nước rỉ và đá rơi xuất hiện cùng nhau.':'Vì nước xiết, vật trôi và mực nước cao đang tác động vào cầu.'}</button><button class="option" data-answer="2">${isHill?'Vì đi lên cao luôn nguy hiểm.':'Vì đường này ngắn nhất.'}</button><p id="feedback" role="status"></p>`);
    document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{if(b.dataset.answer!=='1'){$('feedback').textContent='Hãy ghép các dấu hiệu về điều kiện hiện tại, thay vì kết luận chỉ từ địa hình hoặc loại cầu.';return;}if(!s.judged.includes(route))s.judged.push(route);if(!s.solved.includes(route))s.solved.push(route);save();closePanel();render();speak(isHill?[['Thảo','Đúng. Tìm nơi cao vẫn cần chọn một đường tới đó an toàn. Nhiều dấu hiệu cùng xuất hiện thì không nên mạo hiểm.']]:[['Mạnh','[Bộ đàm] Không qua cầu treo. Nước thượng nguồn đang lên, nhiều cây trôi xuống.'],['Bạn','Mình đã thấy dấu hiệu trước khi bác Mạnh báo. Gần không có nghĩa là an toàn.']],()=>enter('junction'));});
  }
  let crossingProgress=0;
  function crossing(){panel('Qua cầu cùng nhóm','<p>Mạnh dẫn đầu. Thảo đi cùng hai học sinh. Đi đều, không chạy và không dừng trên cầu.</p><p class="good" id="cross-progress">Giữ nút bên dưới hoặc phím Space để đi theo nhóm.</p><button id="hold-cross" class="primary">Giữ để đi cùng nhau →</button>',false);crossingProgress=0;let active=false;const b=$('hold-cross');b.onpointerdown=e=>{e.preventDefault();active=true;b.setPointerCapture(e.pointerId);};b.onpointerup=b.onpointercancel=b.onlostpointercapture=()=>active=false;let previous=performance.now();const frame=now=>{const elapsed=Math.min((now-previous)/1000,.05);previous=now;if($('modal').hidden)return;if(active||held.has(' '))crossingProgress+=elapsed/2.5;$('cross-progress').textContent=`Cả nhóm đang qua cầu · ${Math.min(100,Math.floor(crossingProgress*100))}%`;if(crossingProgress>=1){held.clear();closePanel();s.crossed=true;enter('highroad');return;}requestAnimationFrame(frame);};requestAnimationFrame(frame);}
  function routeGraph(){
    const nodes={gate:[55,235,'Cổng trường'],junction:[200,235,'Ngã ba'],hill:[200,70,'A · Đường đồi'],suspension:[390,70,'B · Cầu treo'],north:[390,235,'C · Đường Bắc'],concrete:[565,235,'Cầu Bắc'],highroad:[660,145,'Đường cao'],refuge:[660,45,'Tập kết']};
    const edges=[['gate','junction'],['junction','hill'],['junction','suspension'],['junction','north'],['north','concrete'],['concrete','highroad'],['highroad','refuge']];
    const paths=edges.map(([a,b])=>{const A=nodes[a],B=nodes[b];return '<path d="M '+A[0]+' '+A[1]+' L '+B[0]+' '+B[1]+'" class="'+(s.visited.includes(a)&&s.visited.includes(b)?'explored':'')+'"/>';}).join('');
    const dots=Object.entries(nodes).map(([id,n])=>'<g class="'+(s.scene===id?'current':s.visited.includes(id)?'visited':'')+'"><circle cx="'+n[0]+'" cy="'+n[1]+'" r="9"/><text x="'+n[0]+'" y="'+(n[1]+29)+'" text-anchor="middle">'+n[2]+'</text></g>').join('');
    return '<div class="diagram-scroll"><svg class="route-diagram" viewBox="0 0 740 285" role="img" aria-label="Bản đồ tám khu vực nối hai chiều, vị trí hiện tại được tô vàng">'+paths+dots+'</svg></div>';
  }
  function showMap(){panel('Ba đường. Một hành trình.',`<p>Khám phá ba tuyến từ ngã ba. Có thể quay lại giữa các khu vực đã nối; dấu hiệu quan sát luôn được giữ.</p>${routeGraph()}<div class="connection">Cổng trường ↔ Ngã ba ↔ A / B / C</div><div class="connection">Đường Bắc ↔ Cầu Bắc ↔ Đường cao ↔ Điểm tập kết</div><div class="route-grid">${['hill','suspension','north'].map((r,i)=>`<div class="route-card"><b>${'ABC'[i]}</b><h3>${D.scenes[r].name.slice(4)}</h3><small>${[450,200,650][i]} m tới điểm tập kết</small><p>${s.judged.includes(r)?'Đã đánh giá: tránh tuyến này.':s.visited.includes(r)?'Đã tới · '+D.required[r].filter(c=>s.clues.includes(c)).length+'/'+D.required[r].length+' dấu hiệu.':'Chưa khảo sát.'}</p></div>`).join('')}</div><h3>Bạn đang ở: ${D.scenes[s.scene].name}</h3><div class="map-end">${D.scenes[s.scene].links.map(to=>`<button data-go="${to}" >${D.scenes[to].name} →</button>`).join('')}</div><p><small>Chọn mũi tên để đi tới. Nếu đường chưa mở, câu đố của khu vực sẽ xuất hiện. Đường quay lại luôn thông.</small></p>`);document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{closePanel();const p=D.scenes[s.scene].spots.find(p=>p.to===b.dataset.go);if(p)walkToSpot(p);else if(b.dataset.go==='highroad')interact({type:'cross'});});}
  function showJournal(){panel('Những điều đã quan sát',`<p>Khoảng cách giúp định hướng. Điều kiện hiện tại mới quyết định tuyến đi.</p><div class="entry"><small>CÂU ĐỐ ĐÃ GIẢI · ${s.solved.length}/8</small><p>${s.solved.map(id=>D.scenes[id].name).join('<br>')||'Chưa giải câu đố nào.'}</p></div>${Object.entries(D.required).map(([r,ids])=>`<div class="entry"><small>${D.scenes[r].name}</small>${ids.map(id=>{const p=D.scenes[r].spots.find(p=>p.id===id);return s.clues.includes(id)?`<p>✓ <strong>${p.label}</strong><br>${p.text}</p>`:'<p>◇ Chưa quan sát dấu hiệu này.</p>';}).join('')}</div>`).join('')}`);}
  function settings(){panel('Nhịp chơi của bạn',`<p>WASD / mũi tên: di chuyển trong vùng quan sát. E: tương tác gần. Bấm dấu hiệu để đi tới và quan sát. Enter: đọc tiếp. M: bản đồ. J: sổ tay. Esc: đóng bảng.</p><div class="buttons"><button id="reduce">Giảm chuyển động: ${reduced()?'bật':'tắt'}</button><button id="restart">Chơi lại chương</button></div><p>Tiến trình được lưu riêng cho Chương 02 trên trình duyệt này.</p>`);$('reduce').onclick=()=>{s.settings.reduced=!s.settings.reduced;save();settings();};$('restart').onclick=()=>{panel('Bắt đầu hành trình mới?','<p>Tiến trình Chương 02 trên trình duyệt này sẽ được thay thế.</p><button id="confirm-restart" class="primary">Chơi lại từ cổng trường</button>');$('confirm-restart').onclick=()=>{closePanel();start(false);};};}
  const reflections=[['Đường chân đồi',['Vì quá xa.','Vì có nhiều dấu hiệu đất không ổn định.','Vì không có cầu.'],1],['Cầu treo',['Vì cầu cũ.','Vì dòng nước và vật trôi đang tác động vào cầu.','Vì đường gần nhất.'],1],['Đường phía Bắc',['Vì cầu làm bằng bê tông.','Vì tuyến hiện ổn định hơn và đã được người phụ trách kiểm tra.','Vì mọi đường cao đều an toàn.'],1]];
  function reflection(i){if(i>=reflections.length){speak([['Thảo','Không chỉ nhìn khoảng cách. Nhớ quan sát nước, địa hình, tình trạng cầu đường và hướng dẫn mới nhất.'],['Duyên','Tiếng gì vậy cô?'],['Mạnh','… Có tiếng đất đá lớn ở phía dưới làng.'],['Minh Anh','[Bộ đàm] Mạnh! Có chuyện ở phía dưới làng!']],()=>{s.complete=true;if(!s.solved.includes('refuge'))s.solved.push('refuge');save();render();showResults();});return;}const [name,answers,right]=reflections[i];panel('Cô Thảo hỏi: “Em nhớ vì sao?”',`<small>${i+1} / 3 · ${name}</small>${answers.map((t,n)=>`<button class="option" data-reflect="${n}">${t}</button>`).join('')}<p id="feedback" role="status"></p>`);document.querySelectorAll('[data-reflect]').forEach(b=>b.onclick=()=>{if(Number(b.dataset.reflect)!==right){$('feedback').textContent='Nhớ lại điều nhóm đã quan sát hôm nay. Loại cầu hay khoảng cách không đủ để kết luận.';return;}closePanel();reflection(i+1);});}
  function showResults(){panel('Ba con đường',`<small class="good">CHƯƠNG 02 HOÀN THÀNH</small><p>Cả nhóm đã qua cầu phía Bắc và lên đường cao. Một tiếng động từ dưới làng mở ra câu chuyện tiếp theo.</p><div class="route-grid"><div class="route-card"><b>13 / 13</b><p>Dấu hiệu đã quan sát</p></div><div class="route-card"><b>3</b><p>Tuyến đường đã cân nhắc</p></div><div class="route-card"><b>Cùng nhau</b><p>Không ai bị bỏ lại</p></div></div><p>✧ Quan sát địa hình<br>✧ Gần không có nghĩa là an toàn<br>✧ Hành trình có người dẫn đường</p><div class="buttons"><button id="review">Xem lại sổ tay</button><button id="replay" class="primary">Chơi lại chương 02</button><a href="index.html">Về chương 01 →</a></div>`,false);$('review').onclick=showJournal;$('replay').onclick=()=>{closePanel();start(false);};}
  $('start').onclick=()=>{if(saved){panel('Bắt đầu một hành trình mới?','<p>Lần chơi mới thay thế tiến trình Chương 02 đã lưu.</p><div class="buttons"><button id="fresh" class="primary">Bắt đầu mới</button><button id="keep">Tiếp tục đã lưu</button></div>');$('fresh').onclick=()=>{closePanel();start(false);};$('keep').onclick=()=>{closePanel();start(true);};}else start(false);};$('resume').hidden=!saved;$('resume').onclick=()=>start(true);$('next').onclick=advance;
  $('sound').onclick=()=>{s.settings.sound=!s.settings.sound;audio.setEnabled(s.settings.sound);audio.start();render();if(s.started)save();};$('map').onclick=()=>{if(s.started&&$('dialogue').hidden)showMap();};$('journal').onclick=()=>{if(s.started&&$('dialogue').hidden)showJournal();};$('settings').onclick=settings;
  function near(){return D.scenes[s.scene].spots.reduce((best,p)=>{const d=Math.abs(p.x-s.position.x)+Math.abs(Math.max(78,p.y)-s.position.y);return d<14&&(!best||d<best.d)?{p,d}:best;},null)?.p;}
  $('interact').onclick=()=>{if(free()){const p=near();if(p)interact(p);else toast('Bấm một dấu hiệu để đi tới và quan sát.');}};
  $('stage').onclick=e=>{if(!free()||e.target.closest('button'))return;const rect=$('stage').getBoundingClientRect();const y=(e.clientY-rect.top)/rect.height*100;if(y>=74)target={x:clampX((e.clientX-rect.left)/rect.width*100),y:Math.max(76,Math.min(91,y))};};
  document.addEventListener('keydown',e=>{if(e.key==='Tab'&&!$('modal').hidden){const elements=[...$('panel').querySelectorAll('button:not(:disabled),a[href],select')];const first=elements[0],end=elements.at(-1);if(e.shiftKey&&(document.activeElement===first||document.activeElement===$('panel'))){e.preventDefault();end?.focus();}else if(!e.shiftKey&&(document.activeElement===end||document.activeElement===$('panel'))){e.preventDefault();first?.focus();}return;}if(e.target.matches('select')&&!$('modal').hidden&&e.key!=='Escape')return;const k=e.key.length===1?e.key.toLowerCase():e.key;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown',' '].includes(k))e.preventDefault();if(k==='Escape'){if(!$('modal').hidden&&$('hold-cross'))return;if(!$('modal').hidden)closePanel();else settings();return;}if((k==='Enter'||k===' ')&&!$('dialogue').hidden){if(!e.repeat)advance();return;}if(!$('modal').hidden){if($('hold-cross')&&k===' ')held.add(' ');return;}if(!free())return;if(['w','a','s','d','ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(k)){held.add(k);target=null;}if(e.repeat)return;if(k==='e')$('interact').click();if(k==='m')showMap();if(k==='j')showJournal();});
  document.addEventListener('keyup',e=>held.delete(e.key.length===1?e.key.toLowerCase():e.key));window.addEventListener('blur',()=>{held.clear();target=null;if(s.started)save();});window.addEventListener('pagehide',()=>{if(s.started)save();});document.addEventListener('visibilitychange',()=>{if(document.hidden){held.clear();audio.ctx?.suspend();}else if(s.started)audio.start();});
  document.querySelectorAll('[data-key]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();if(free()){target=null;held.add(b.dataset.key);b.setPointerCapture(e.pointerId);}};b.onpointerup=b.onpointercancel=b.onlostpointercapture=()=>{held.delete(b.dataset.key);save();};});
  const canvas=$('rain'),ctx=canvas.getContext('2d');let drops=[];function resize(){canvas.width=$('stage').clientWidth;canvas.height=$('stage').clientHeight;drops=Array.from({length:90},()=>({x:Math.random()*canvas.width,y:Math.random()*canvas.height,v:450+Math.random()*250}));}new ResizeObserver(resize).observe($('stage'));resize();
  function frame(now){const dt=Math.min((now-last)/1000,.04);last=now;tick+=dt;ctx.clearRect(0,0,canvas.width,canvas.height);if(!reduced()){ctx.strokeStyle='#d7e9e230';ctx.lineWidth=1;ctx.beginPath();for(const d of drops){d.y+=d.v*dt;d.x-=d.v*.2*dt;if(d.y>canvas.height){d.y=-30;d.x=Math.random()*canvas.width;}ctx.moveTo(d.x,d.y);ctx.lineTo(d.x-5,d.y+20);}ctx.stroke();}
    let moving=false;if(free()){let dx=0,dy=0;if(target){const x=target.x-s.position.x,y=target.y-s.position.y,dist=Math.hypot(x,y);if(dist<.5){const action=target.action;target=null;action?.();}else{dx=x/dist;dy=y/dist;}}else{dx=Number(held.has('d')||held.has('ArrowRight'))-Number(held.has('a')||held.has('ArrowLeft'));dy=Number(held.has('s')||held.has('ArrowDown'))-Number(held.has('w')||held.has('ArrowUp'));const n=Math.hypot(dx,dy);if(n>1){dx/=n;dy/=n;}}if(dx||dy){moving=true;s.position.x=clampX(s.position.x+dx*22*dt);s.position.y=Math.max(76,Math.min(91,s.position.y+dy*13*dt));$('party').style.left=s.position.x+'%';$('party').style.top=s.position.y+'%';}}
    $('party').classList.toggle('walking',moving&&!reduced());const pose=moving&&!reduced()?(Math.floor(tick*7)%2?'walk-1':'walk-2'):'idle';if($('player').dataset.pose!==pose){$('player').src=`assets/characters/ban/${pose}.png`;$('player').dataset.pose=pose;}if(now>toastUntil)$('location-toast').classList.remove('visible');requestAnimationFrame(frame);
  }
  render();requestAnimationFrame(frame);
})();
